routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RankController;
use App\Http\Controllers\TravelController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'formLogin'])->middleware('guest')->name('login');
Route::post('/', [AuthController::class, 'login'])->middleware('guest');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/profile', [ProfileController::class, 'profile'])->middleware('auth')->name('profile');

Route::group([
    'prefix' => 'group',
    'as' => 'group.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [GroupController::class, 'list'])->name('list');
    Route::get('/add', [GroupController::class, 'formAdd'])->name('add');
    Route::post('/add', [GroupController::class, 'add']);
    Route::get('/show/{id}', [GroupController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [GroupController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [GroupController::class, 'update']);
    Route::post('/delete/{id}', [GroupController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'rank',
    'as' => 'rank.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [RankController::class, 'list'])->name('list');
    Route::get('/add', [RankController::class, 'formAdd'])->name('add');
    Route::post('/add', [RankController::class, 'add']);
    Route::get('/show/{id}', [RankController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [RankController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [RankController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'position',
    'as' => 'position.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [PositionController::class, 'list'])->name('list');
    Route::get('/add', [PositionController::class, 'formAdd'])->name('add');
    Route::post('/add', [PositionController::class, 'add']);
    Route::get('/show/{id}', [PositionController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [PositionController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [PositionController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [UserController::class, 'list'])->name('list');
    Route::get('/add', [UserController::class, 'formAdd'])->name('add');
    Route::post('/add', [UserController::class, 'add']);
    Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [UserController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [UserController::class, 'update']);
    Route::post('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'travel',
    'as' => 'travel.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [TravelController::class, 'list'])->name('list');
    Route::get('/download', [TravelController::class, 'download'])->name('download');
    Route::get('/show/{id}', [TravelController::class, 'show'])->name('show');
    Route::get('/add', [TravelController::class, 'formAdd'])->name('add');
    Route::post('/add', [TravelController::class, 'add']);
    Route::get('/edit/{id}', [TravelController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [TravelController::class, 'update']);
    Route::post('/delete/{id}', [TravelController::class, 'delete'])->name('delete');

    Route::post('/add-user/{id}', [TravelController::class, 'addUser'])->name('add.user');
    Route::post('/remove-user/{id}', [TravelController::class, 'removeUser'])->name('remove.user');
    Route::post('/check-travel', [TravelController::class, 'checkTravel'])->name('check.travel');
    Route::post('/delete-user/{travelUserID}', [TravelController::class, 'deleteUser'])->name('delete.user');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'nip',
        'role_id',
        'group_id',
        'position_id',
        'rank_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function rank() {
        return $this->belongsTo(Rank::class, 'rank_id');
    }

    public function group() {
        return $this->belongsTo(Group::class, 'group_id');
    }

    public function position() {
        return $this->belongsTo(Position::class, 'position_id');
    }

    public function getRankNameAttribute() {
        $data   = $this->rank()->first();
        if( !$data ) {
            return 'Belum ada data';
        }

        return $data->name;
    }

    public function getGroupNameAttribute() {
        $data   = $this->group()->first();
        if( !$data ) {
            return 'Belum ada data';
        }

        return $data->name;
    }

    public function getPositionNameAttribute() {
        $data   = $this->position()->first();
        if( !$data ) {
            return 'Belum ada data';
        }

        return $data->name;
    }

    public function getRoleNameAttribute() {
        if( $this->role_id == 1 ) {
            return 'Admin';
        }
        return 'User';
    }
}

resources/views/profile.blade.php
@extends('layouts.lte')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Profile</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item active">Profile {{ Auth::user()->name }}</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row">
      <div class="col-md-6">

        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Profile</h3>
          </div>

          <div class="card-body">
            <table class="table table-full">
              <tr>
                <td>Nama Lengkap</td>
                <td>{{ Auth::user()->name }}</td>
              </tr>
              <tr>
                <td>Username</td>
                <td>{{ Auth::user()->username }}</td>
              </tr>
              <tr>
                <td>NIP</td>
                <td>{{ Auth::user()->nip }}</td>
              </tr>
              <tr>
                <td>Pangkat</td>
                <td>{{ Auth::user()->rank_name }}</td>
              </tr>
              <tr>
                <td>Golongan</td>
                <td>{{ Auth::user()->group_name }}</td>
              </tr>
              <tr>
                <td>Jabatan</td>
                <td>{{ Auth::user()->position_name }}</td>
              </tr>
              <tr>
                <td>Hak Akses</td>
                <td>{{ Auth::user()->role_name }}</td>
              </tr>
            </table>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

@endsection