routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RankController;
use App\Http\Controllers\TravelController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'formLogin'])->middleware('guest')->name('login');
Route::post('/', [AuthController::class, 'login'])->middleware('guest');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/profile', [ProfileController::class, 'profile'])->middleware('auth')->name('profile');

Route::group([
    'prefix' => 'group',
    'as' => 'group.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [GroupController::class, 'list'])->name('list');
    Route::get('/add', [GroupController::class, 'formAdd'])->name('add');
    Route::post('/add', [GroupController::class, 'add']);
    Route::get('/show/{id}', [GroupController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [GroupController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [GroupController::class, 'update']);
    Route::post('/delete/{id}', [GroupController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'rank',
    'as' => 'rank.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [RankController::class, 'list'])->name('list');
    Route::get('/add', [RankController::class, 'formAdd'])->name('add');
    Route::post('/add', [RankController::class, 'add']);
    Route::get('/show/{id}', [RankController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [RankController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [RankController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'position',
    'as' => 'position.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [PositionController::class, 'list'])->name('list');
    Route::get('/add', [PositionController::class, 'formAdd'])->name('add');
    Route::post('/add', [PositionController::class, 'add']);
    Route::get('/show/{id}', [PositionController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [PositionController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [PositionController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [UserController::class, 'list'])->name('list');
    Route::get('/add', [UserController::class, 'formAdd'])->name('add');
    Route::post('/add', [UserController::class, 'add']);
    Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [UserController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [UserController::class, 'update']);
    Route::post('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'travel',
    'as' => 'travel.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [TravelController::class, 'list'])->name('list');
    Route::get('/download', [TravelController::class, 'download'])->name('download');
    Route::get('/show/{id}', [TravelController::class, 'show'])->name('show');
    Route::get('/add', [TravelController::class, 'formAdd'])->name('add');
    Route::post('/add', [TravelController::class, 'add']);
    Route::get('/edit/{id}', [TravelController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [TravelController::class, 'update']);
    Route::post('/delete/{id}', [TravelController::class, 'delete'])->name('delete');

    Route::post('/add-user/{id}', [TravelController::class, 'addUser'])->name('add.user');
    Route::post('/remove-user/{id}', [TravelController::class, 'removeUser'])->name('remove.user');
    Route::post('/check-travel', [TravelController::class, 'checkTravel'])->name('check.travel');
    Route::post('/delete-user/{travelUserID}', [TravelController::class, 'deleteUser'])->name('delete.user');
});

app/Models/Rank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rank extends Model
{
    use HasFactory;

    protected $fillable     = [
        'name',
    ];
}

app/Http/Controllers/RankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Rank;

class RankController extends Controller
{
    public function list()
    {
        $rank   = Rank::all();
        return view('rank.list', compact('rank'));
    }

    public function formAdd()
    {
        return view('rank.add');
    }

    public function add(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $payload = $request->only(['name']);

        $rank = Rank::create($payload);

        return redirect(route('rank.list'))->with('success', 'Tambah Pangkat');
    }
    
    public function formUpdate($id)
    {
        $rank = Rank::find($id);
        return view('rank.edit', compact('rank'));
    }

    public function update(Request $request, $id)
    {  
        $this->validate($request, [
            'name' => 'required'
        ]);

        $rank = Rank::find($id);

        $payload = $request->only(['name']);

        $rank->update($payload);
        return redirect(route('rank.list'))->with('success', 'Ubah Pangkat');
    }

    public function delete($id)
    {
        $rank = Rank::find($id);
        $rank->delete();
        return redirect(route('rank.list'))->with('success', 'Hapus Pangkat');
    }
}

resources/views/rank/add.blade.php
@extends('layouts.lte')

@push('style')

@endpush

@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        {{-- <h1 class="m-0">Pangkat</h1> --}}
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Master Data</a></li>
          <li class="breadcrumb-item"><a href="{{ route('rank.list') }}">Pangkat</a></li>
          <li class="breadcrumb-item active">Tambah</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row justify-content-center">
      <div class="col-md-6 col-offset-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Tambah Pangkat</h3>
          </div>
          <form method="post" action="/rank/add">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="name">Nama Pangkat</label>
                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" id="name" name="name" placeholder="Masukkan nama pangkat">
                @foreach($errors->get('name') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-success">Tambah</button>
            </div>
          </form>
        </div>

      </div>

    </div>

  </div>
</section>

@endsection

@push('script')

@endpush

resources/views/rank/edit.blade.php
@extends('layouts.lte')

@push('style')

@endpush

@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        {{-- <h1 class="m-0">Pangkat</h1> --}}
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Master Data</a></li>
          <li class="breadcrumb-item"><a href="{{ route('rank.list') }}">Pangkat</a></li>
          <li class="breadcrumb-item active">Ubah</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row justify-content-center">
      <div class="col-md-6 col-offset-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Ubah Pangkat</h3>
          </div>
          <form method="post" action="/rank/edit/{{ $rank->id }}">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="name">Nama Pangkat</label>
                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" id="name" name="name" placeholder="Masukkan nama pangkat" value="{{ $rank->name }}">
                @foreach($errors->get('name') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Ubah</button>
            </div>
          </form>
        </div>

      </div>

    </div>

  </div>
</section>

@endsection

@push('script')

@endpush

resources/views/rank/list.blade.php
@extends('layouts.lte')

@push('style')

<link rel="stylesheet" href="{{ url('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ url('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ url('plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
@endpush

@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Pangkat</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a>Master Data</a></li>
          <li class="breadcrumb-item active">Pangkat</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <div class="d-flex justify-content-between align-items-center w-100">
              <h3 class="card-title">List Pangkat</h3>
              <a href="{{ route('rank.add') }}" class="btn btn-sm btn-success font-weight-bold">
                Tambah
              </a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="rank" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama Pangkat</th>
                  <th>Dibuat Pada</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($rank as $item)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $item->name }}</td>
                  <td>{{ $item->created_at }}</td>
                  <td>
                    <a href="{{ route('rank.update', ['id' => $item->id]) }}" class="btn btn-sm btn-warning">
                      <i class="fas fa-edit"></i>
                    </a>
                    <button data-id="{{ $item->id }}" data-name="{{ $item->name }}" class="ml-1 btn btn-sm btn-danger delete-confirm">
                      <i class="fas fa-trash-alt"></i>
                    </button>
                  </td>
                </tr>
                @endforeach
              </tbody>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Nama Pangkat</th>
                  <th>Dibuat Pada</th>
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
      </div>

    </div>

  </div>
</section>

@endsection

@push('script')

<script src="{{ url('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ url('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ url('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ url('plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ url('plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script>
  $(function () {
    $('#rank').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
      "rowCallback": function(row, data) {
        $('.delete-confirm').click(function(event) {
        var id = $(this).data('id');
        var name = $(this).data('name');
        event.preventDefault();
        Swal.fire({
          title: `Hapus "${name}"?`,
          text: 'Anda tidak akan dapat mengembalikan ini!',
          icon: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Ya, Hapus!',
          cancelButtonText: 'Batal',
          reverseButtons: true,
        }).then(result => {
          if (result.isConfirmed) {
            $.ajax({
              url: `/rank/delete/${id}`,
              type: 'POST',
              data: {
                id: id,
                '_token': '{{ csrf_token() }}',
              },
              success: function () {
                Swal.fire({
                  title: 'Success',
                  text: 'Hapus Pangkat!',
                  icon: 'success',
                  dangerMode: true,
                }).then(function() {
                  location.reload();
                });
              },
              error: function (xhr, status, error) {
                var err = JSON.parse(xhr.responseText);
                Swal.fire({
                  title: 'Error',
                  text: err?.Message,
                  icon: 'error',
                });
              }
            })
          }
        });
      })
      }
    });
  });

</script>
@endpush