routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RankController;
use App\Http\Controllers\TravelController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'formLogin'])->middleware('guest')->name('login');
Route::post('/', [AuthController::class, 'login'])->middleware('guest');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/profile', [ProfileController::class, 'profile'])->middleware('auth')->name('profile');

Route::group([
    'prefix' => 'group',
    'as' => 'group.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [GroupController::class, 'list'])->name('list');
    Route::get('/add', [GroupController::class, 'formAdd'])->name('add');
    Route::post('/add', [GroupController::class, 'add']);
    Route::get('/show/{id}', [GroupController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [GroupController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [GroupController::class, 'update']);
    Route::post('/delete/{id}', [GroupController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'rank',
    'as' => 'rank.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [RankController::class, 'list'])->name('list');
    Route::get('/add', [RankController::class, 'formAdd'])->name('add');
    Route::post('/add', [RankController::class, 'add']);
    Route::get('/show/{id}', [RankController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [RankController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [RankController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'position',
    'as' => 'position.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [PositionController::class, 'list'])->name('list');
    Route::get('/add', [PositionController::class, 'formAdd'])->name('add');
    Route::post('/add', [PositionController::class, 'add']);
    Route::get('/show/{id}', [PositionController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [PositionController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [PositionController::class, 'update']);
    Route::post('/delete/{id}', [RankController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [UserController::class, 'list'])->name('list');
    Route::get('/add', [UserController::class, 'formAdd'])->name('add');
    Route::post('/add', [UserController::class, 'add']);
    Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}', [UserController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [UserController::class, 'update']);
    Route::post('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'travel',
    'as' => 'travel.',
    'middleware' => 'auth',
], function() {
    Route::get('/list', [TravelController::class, 'list'])->name('list');
    Route::get('/download', [TravelController::class, 'download'])->name('download');
    Route::get('/show/{id}', [TravelController::class, 'show'])->name('show');
    Route::get('/add', [TravelController::class, 'formAdd'])->name('add');
    Route::post('/add', [TravelController::class, 'add']);
    Route::get('/edit/{id}', [TravelController::class, 'formUpdate'])->name('update');
    Route::post('/edit/{id}', [TravelController::class, 'update']);
    Route::post('/delete/{id}', [TravelController::class, 'delete'])->name('delete');

    Route::post('/add-user/{id}', [TravelController::class, 'addUser'])->name('add.user');
    Route::post('/remove-user/{id}', [TravelController::class, 'removeUser'])->name('remove.user');
    Route::post('/check-travel', [TravelController::class, 'checkTravel'])->name('check.travel');
    Route::post('/delete-user/{travelUserID}', [TravelController::class, 'deleteUser'])->name('delete.user');
});

app/Models/Travel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Travel extends Model
{
    use HasFactory;

    protected $fillable     = [
        'code',
        'necessity',
        'underlying',
        'letter_date',
        'start_date',
        'end_date',
        'destination',
    ];

    protected $casts    = [
        'letter_date' => 'datetime',
        'start_date' => 'datetime',
        'end_date'  => 'datetime',
    ];

    public function travelUsers() {
        return $this->hasMany(TravelUser::class, 'travel_id');
    }
}

app/Http/Controllers/TravelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Travel;
use App\Models\TravelUser;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class TravelController extends Controller
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request  = $request;
    }

    public function list()
    {
        $auth   = Auth::user();
        if( $auth->role_id == 1 ) {
            $travels    = Travel::orderBy('id', 'desc')->get();
        } else {
            $userTravels    = TravelUser::where('user_id', '=', $auth->id)->get();
            $travelIDs  = [];
            foreach ($userTravels as $key => $value) {
                array_push($travelIDs, $value->travel_id);
            }
            $travels    = Travel::whereIn('id', $travelIDs)->get();
        }

        return view('travel.list', compact('travels'));
    }

    public function download()
    {
        $auth   = Auth::user();
        if( $auth->role_id == 1 ) {
            $travels    = Travel::orderBy('id', 'desc')->get();
        } else {
            $userTravels    = TravelUser::where('user_id', '=', $auth->id)->get();
            $travelIDs  = [];
            foreach ($userTravels as $key => $value) {
                array_push($travelIDs, $value->travel_id);
            }
            $travels    = Travel::whereIn('id', $travelIDs)->get();
        }

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        $sheet->getColumnDimension('A')->setWidth(15, 'px');
        $sheet->getColumnDimension('B')->setWidth(15, 'px');

        $rows   = 2;
        $cellCode           = 'C' . $rows;
        $sheet->setCellValue($cellCode, 'No. Surat Tugas');
        $cellLetterDate     = 'D' . $rows;
        $sheet->setCellValue($cellLetterDate, 'Tanggal Surat Tugas');
        $cellName           = 'E' . $rows;
        $sheet->setCellValue($cellName, 'Nama Lengkap');
        $cellNip            = 'F' . $rows;
        $sheet->setCellValue($cellNip, 'NIP');
        $cellRank           = 'G' . $rows;
        $sheet->setCellValue($cellRank, 'Pangkat');
        $cellGroup          = 'H' . $rows;
        $sheet->setCellValue($cellGroup, 'Golongan');
        $cellPosition       = 'I' . $rows;
        $sheet->setCellValue($cellPosition, 'Jabatan');
        $cellNecesity       = 'J' . $rows;
        $sheet->setCellValue($cellNecesity, 'Keperluan');
        $cellDestination    = 'K' . $rows;
        $sheet->setCellValue($cellDestination, 'Tujuan');
        $cellStartDate      = 'L' . $rows;
        $sheet->setCellValue($cellStartDate, 'Tanggal Mulai');
        $cellEndDate        = 'M' . $rows;
        $sheet->setCellValue($cellEndDate, 'Tanggal Selesai');
        $rows++;

        foreach ($travels as $item) {
            $travelUsers  = $item->travelUsers;
            foreach ($travelUsers as $travelUser) {
                $user   = $travelUser->user;
                $cellCode           = 'C' . $rows;
                $sheet->setCellValue($cellCode, $item->code);
                $cellLetterDate     = 'D' . $rows;
                $sheet->setCellValue($cellLetterDate, $item->letter_date);
                $cellName           = 'E' . $rows;
                $sheet->setCellValue($cellName, $user->name);
                $cellNip            = 'F' . $rows;
                $sheet->setCellValue($cellNip, $user->nip);
                $cellRank           = 'G' . $rows;
                $sheet->setCellValue($cellRank, $user->rank_name);
                $cellGroup          = 'H' . $rows;
                $sheet->setCellValue($cellGroup, $user->group_name);
                $cellPosition       = 'I' . $rows;
                $sheet->setCellValue($cellPosition, $user->position_name);
                $cellNecesity       = 'J' . $rows;
                $sheet->setCellValue($cellNecesity, $item->necessity);
                $cellDestination    = 'K' . $rows;
                $sheet->setCellValue($cellDestination, $item->destination);
                $cellStartDate      = 'L' . $rows;
                $sheet->setCellValue($cellStartDate, $item->start_date->format('Y-m-d'));
                $cellEndDate        = 'M' . $rows;
                $sheet->setCellValue($cellEndDate, $item->end_date->format('Y-m-d'));
                $rows++;
            }
        }

        $sheet->getStyle('C2:M' . $rows)->getBorders()->getAllBorders()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN);

        $spreadsheet->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('K')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
        $spreadsheet->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="Perjalanan Dinas.xlsx"');
        header('Cache-Control: max-age=0');

        $writer = new Xlsx($spreadsheet);
        $writer->save('php://output');
    }

    public function show($id)
    {
        $auth   = Auth::user();
        $travel     = Travel::find($id);

        if( !$travel ) {
            return redirect( route('travel.list') )->withErrors('Travel tidak ditemukan');
        }

        if( $auth->role_id != 1 ) {
            $exist  = TravelUser::where('user_id', '=', $auth->id)->where('travel_id', '=', $id)->first();
            if( !$exist ) {
                return redirect( route('travel.list') )->withErrors('Travel tidak ditemukan');
            }
        }

        return view('travel.show', compact('travel'));
    }

    public function formAdd()
    {
        $users  = User::orderBy('name', 'ASC')->get();
        return view('travel.add', compact('users'));
    }

    public function add()
    {
        $this->validate($this->request, [
            'letter_date' => ['required'],
            'code' => ['required'],
            'start_date' => ['required'],
            'end_date' => ['required'],
            'user_id' => ['required'],
        ]);

        $payloads   = $this->request->only(['letter_date', 'code', 'start_date', 'end_date', 'necessity', 'destination']);

        $userIDs    = $this->request->user_id;

        $travel     = Travel::create($payloads);

        foreach ($userIDs as $key => $id) {
            $payloads   = [
                'travel_id' => $travel->id,
                'user_id'   => $id,
            ];
            $travelUser     = TravelUser::create($payloads);
        }

        return redirect( route('travel.list') )->with('success', 'Berhasil Menambahkan Data Perjalanan Dinas');
    }
    
    public function formUpdate($id)
    {
        $travel     = Travel::find($id);
        if( !$travel ) {
            return redirect( route('travel.list') )->withErrors('Tidak ditemukan');
        }

        $travelUsers    = TravelUser::where('travel_id', '=', $id)->get();
        $userIDs    = [];
        foreach ($travelUsers as $item) {
            array_push($userIDs, $item->user_id);
        }

        $users  = User::all();

        $selectedUsers  = User::whereIn('id', $userIDs)->get();

        return view('travel.edit', compact('travel', 'users', 'selectedUsers'));
    }

    public function update($id)
    {
        $travel     = Travel::find($id);

        if( !$travel ) {
            return redirect( route('travel.list') )->withErrors('Tidak ditemukan');
        }

        $this->validate($this->request, [
            'letter_date' => ['required'],
            'code' => ['required'],
            'start_date' => ['required'],
            'end_date' => ['required'],
            'user_id' => ['required'],
        ]);

        $payloads   = $this->request->only(['letter_date', 'code', 'start_date', 'end_date', 'necessity', 'destination']);

        $userIDs    = $this->request->user_id;

        $travelUsers    = $travel->travelUsers;

        foreach ($userIDs as $key => $id) {
            $insert     = true;

            foreach ($travelUsers as $travelUser) {
                if( $travelUser->user_id == $id ) {
                    $insert     = false;
                }
            }

            if( $insert ) {
                $payloads   = [
                    'travel_id' => $travel->id,
                    'user_id'   => $id,
                ];
    
                $travelUser     = TravelUser::create($payloads);
            }
        }

        $travel->update($payloads);

        return redirect( route('travel.list') )->with('success', 'Berhasil mengupdate Perjalanan Dinas');
    }

    public function delete($id)
    {
        $travel   = Travel::find($id);

        if( !$travel ) {
            return response()->json(['message' => 'Perjalanan Dinas tidak ditemukan', 'errors' => []], 404);
        }

        TravelUser::where('travel_id', '=', $id)->delete();
        $travel->delete();

        return response()->json(['message' => 'Berhasil menghapus Perjalanan Dinas']);
    }

    public function checkTravel()
    {
        $this->validate($this->request, [
            'user_id' => ['required'],
            'start_date' => ['required'],
            'end_date' => ['required'],

resources/views/travel/edit.blade.php
@extends('layouts.lte')

@push('style')

@endpush

@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        {{-- <h1 class="m-0">Pangkat</h1> --}}
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ route('travel.list') }}">Perjalanan Dinas</a></li>
          <li class="breadcrumb-item active">Edit {{ $travel->code }}</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row justify-content-center">
      <div class="col-md-6 col-offset-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Edit Perjalanan Dinas</h3>
          </div>
          <form method="post" id="form-add-travel" action="{{ route('travel.update', ['id' => $travel->id]) }}">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="code">No. Surat Tugas</label>
                <input type="text" class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" id="code" name="code" placeholder="Masukkan No. Surat Tugas" value="{{ $travel->code }}" required>
                @foreach($errors->get('code') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div class="form-group">
                <label for="letter_date">Tanggal Surat Tugas</label>
                <input type="date" class="form-control {{ $errors->has('letter_date') ? 'is-invalid' : '' }}" id="letter_date" name="letter_date" value="{{ $travel->letter_date->format('Y-m-d') }}" placeholder="Masukkan Tanggal Surat Tugas" required>
                @foreach($errors->get('letter_date') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div class="form-group">
                <label for="necessity">Keperluan</label>
                <textarea class="form-control {{ $errors->has('necessity') ? 'is-invalid' : '' }}" id="necessity" name="necessity" placeholder="Masukkan Keperluan" required rows="5">{{ $travel->necessity }}</textarea>
                @foreach($errors->get('necessity') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div class="form-group">
                <label for="destination">Tujuan</label>
                <input type="text" class="form-control {{ $errors->has('destination') ? 'is-invalid' : '' }}" id="destination" name="destination" placeholder="Masukkan Tujuan" value="{{ $travel->destination }}" required>
                @foreach($errors->get('destination') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div class="form-group">
                <label for="start_date">Tanggal Mulai</label>
                <input type="date" class="form-control {{ $errors->has('start_date') ? 'is-invalid' : '' }}" id="start_date" name="start_date" placeholder="Masukkan Tanggal Mulai" value="{{ $travel->start_date->format('Y-m-d') }}" required>
                @foreach($errors->get('start_date') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div class="form-group">
                <label for="end_date">Tanggal Selesai</label>
                <input type="date" class="form-control {{ $errors->has('end_date') ? 'is-invalid' : '' }}" id="end_date" name="end_date" placeholder="Masukkan Tanggal Selesai" value="{{ $travel->end_date->format('Y-m-d') }}" required>
                @foreach($errors->get('end_date') as $msg)
                  <span class="text-danger text-small">{{ $msg }}</span>
                @endforeach
              </div>

              <div id="users" class="form-group">
                <label for="users">Pengguna</label>

                <div id="user-list-container">
                  <table id="user-list" class="table table-hover">
                    
                  </table>
                </div>

                <button class="btn btn-sm btn-success" type="button" id="btn-add-user"  data-toggle="modal" data-target="#addUser"><i class="fas fa-plus"></i></button>
              </div>
              
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-success">Update</button>
            </div>
          </form>
        </div>

      </div>

    </div>

  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="addUser" tabindex="-1" role="dialog" aria-labelledby="addUserLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addUserLabel">Tambah Pengguna</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" id="form-add-user" method="post"></form>
        <p class="text-center" id="loading">Loading...</p>
        <div class="form-group d-none" id="user-input">
          <label for="user-id" class="d-block">Pengguna</label>
          <select name="user-id" id="user-id" class="form-control select2 d-block" style="width: 100%">
            
          </select>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button form="form-add-user" class="btn btn-primary">Tambah</button>
      </div>
    </div>
  </div>
</div>

@endsection

@push('script')
<script>
const users = @json($users)


const selectedUsers = @json($selectedUsers)


const travelID  = {{ $travel->id }};

const deleteUser  = async (id) => {

  const user = {
      user_id: id,
  }

  await fetch('{{ route('travel.remove.user', ['id' => $travel->id]) }}', {
      method: 'POST',
      headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
      },
      body: JSON.stringify(user),
  })
  .then(response => response.json())
  .then(json => {
    if( json.errors !== undefined ) {
        showError(json.message)
        return
    }

    while(selectedUsers.length > 0) {
        selectedUsers.pop()
    }
    selectedUsers.forEach(item => {
        let insert  = true
        if( item.id == user.id ) {
        insert = false
        }
        if( insert ) {
        selectedUsers.push(item)
        }
    })
    showSuccess('Berhasil menghapus ' + user.name + ' dari Daftar')
    
    renderSelectedUsers()
  })
  .catch(error => showError(error))

}

const showError = (msg) => {
  $(document).Toasts('create', {
    class: 'bg-danger',
    title: 'Gagal',
    body: msg
  })
}

const showSuccess   = (msg) => {
  $(document).Toasts('create', {
    class: 'bg-success',
    title: 'Berhasil',
    body: msg
  })
}

const renderSelectedUsers = () => {

  const tableUserList  = document.querySelector('#user-list')
  tableUserList.innerHTML = ''
  
  selectedUsers.forEach(item => {
    const tr  = document.createElement('tr')
    tr.setAttribute('data-id', item.id)
    tableUserList.appendChild(tr)

    const tdName  = document.createElement('td')
    tr.appendChild(tdName)
    tdName.innerHTML  = item.name

    const tdBtn   = document.createElement('td')
    tdBtn.setAttribute('style', 'width: 15px;')
    tr.appendChild(tdBtn)

    const btn     = document.createElement('button')
    btn.setAttribute('class', 'btn btn-sm btn-danger')
    btn.setAttribute('type', 'button')
    btn.addEventListener('click', e => {
      deleteUser(item)
    })
    tdBtn.appendChild(btn)

    const i       = document.createElement('i')
    i.setAttribute('class', 'fas fa-window-close')
    btn.appendChild(i)
  })

  
}

renderSelectedUsers()

const loadUser  = () => {
  const selectInput = document.querySelector('#user-id')
  selectInput.innerHTML = ''

  const placeHolder  = document.createElement('option')
  placeHolder.innerHTML = '-- Pilih Pengguna --'
  selectInput.appendChild(placeHolder)

  const availableUsers  = []

  users.forEach(item => {
    let insert = true
    selectedUsers.forEach(select => {
      if( item.id == select.id ) {
        insert = false
      }
    })

    if( insert ) {
      availableUsers.push(item)
    }
  })

  availableUsers.forEach(item => {
    const option  = document.createElement('option')
    option.setAttribute('value', item.id)
    option.innerHTML = item.name

    selectInput.appendChild(option)
  })

  $('#user-input').removeClass('d-none')
  $('#loading').addClass('d-none')
}

const checkTravelUser = async (date, user) => {
  const body = {
    date,
    user_id: user.id,
  }

  await fetch('{{ route('travel.check.travel') }}', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    }
  })
  .then(response => response.json())
  .then(json => {
    if( json.errors !== undefined ) {
      showError(json.message)
      return
    }

    if( json.message ) {
      showSuccess(json.message)
      selectedUsers.push(user)

      $('#addUser').modal('hide')
      renderSelectedUsers()
      return
    }
  }).catch(error => {
    if( error.message ) {
      showError(error.message)
    }
  })
}

$(function () {
  $('#start_date').change(e => {
    let item  = e.target
    let value = item.value
    
    if( value ) {
      $('#users').removeClass('d-none')
    }
  })

  $('#form-add-travel').submit(e => {
    e.preventDefault()

    const formAddTravel   = document.querySelector('#form-add-travel')

    selectedUsers.forEach((item, key) => {
      const input   = document.createElement('input')
      input.setAttribute('name', 'user_id[' + key + ']')
      input.setAttribute('type', 'hidden')
      input.setAttribute('value', item.id)
      formAddTravel.appendChild(input)
    })

    formAddTravel.submit()
  })

  $('#form-add-user').submit(e => {
    e.preventDefault()
    const val = $('#user-id').val()
    const letterDate  = $('#start_date').val()

    let user

    users.forEach(item => {
      if( item.id == val ) {
        user  = item
      }
    });

    checkTravelUser(letterDate, user)
  })

  $('#addUser').on('show.bs.modal', e => {
    loadUser()
  })
})
</script>
@endpush

resources/views/travel/show.blade.php
@extends('layouts.lte')

@push('style')

@endpush

@section('content')

<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        {{-- <h1 class="m-0">Pangkat</h1> --}}
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ route('travel.list') }}">Perjalanan Dinas</a></li>
          <li class="breadcrumb-item active">Perjalanan Dinas {{ $travel->code }}</li>
        </ol>
      </div>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Perjalanan Dinas</h3>
          </div>
          <div class="card-body">
            <table class="table table-full">
              <tr>
                <td>No. Surat</td>
                <td>{{ $travel->code }}</td>
              </tr>
              <tr>
                <td>Tanggal Surat</td>
                <td>{{ $travel->letter_date->format('Y-m-d') }}</td>
              </tr>
              <tr>
                <td>Tanggal Mulai</td>
                <td>{{ $travel->start_date->format('Y-m-d') }}</td>
              </tr>
              <tr>
                <td>Tanggal Selesai</td>
                <td>{{ $travel->end_date->format('Y-m-d') }}</td>
              </tr>
              <tr>
                <td>Keperluan</td>
                <td>{{ $travel->necessity }}</td>
              </tr>
              <tr>
                <td>Peserta</td>
                <td>
                    <ol class="pl-3">
                        @foreach ($travel->travelUsers as $item)
                        <li>{{ $item->user->name }}</li>
                        @endforeach
                    </ol>
                </td>
              </tr>
            </table>
          </div>
        </div>

      </div>

    </div>

  </div>
</section>

@endsection